# Copyright (C) 2025 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/RalfMende/MobileStationWebApp.git
PKG_SOURCE_VERSION:=main